### ISSUE TITLE
Client does nothing under macOS High Sierra

### ISSUE THREAD

**Issue by jwolz** [jwolz/yajhfc#61]
**[Original report](https://bitbucket.org/jonaswolz/yajhfc/issue/61) by Anonymous.**

----------------------------------------

Hey. 
I recently upgraded to a new MacbookPro with High Sierra version 10.31.1 and Java version 10.0.2
I downloaded the client version 6.2., unpacked it and started it.

The program also appears in the Dock, but no window opens.

**Comment by TheCranston** [comment]
Is the issue is around the `com.apple.{eawt,eio}` APIs being deprecated?  The change is documented at: https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8048731   

I can confirm that it it fails with JRE 11.
`SEVERE: An uncaught exception occurred during event dispatching (Thread: Thread[AWT-EventQueue-0,6,main]):
java.lang.NoClassDefFoundError: com/apple/eawt/ApplicationListener
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:377)
	at yajhfc.macosx.MacOSXSupport.getInstance(MacOSXSupport.java:64)
	at yajhfc.MainWin.initializePlatformSpecifics(MainWin.java:2024)
	at yajhfc.MainWin.initialize(MainWin.java:1939)
	at yajhfc.launch.Launcher2$NewInstRunner.run(Launcher2.java:528)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassNotFoundException: com.apple.eawt.ApplicationListener
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 19 more
`

**Comment by jwolz** [comment]
Thank you, that would explain the problem.

I will look if I can modify the code so that it fails more gracefully.
Only problem is that I currently do not have access to a Mac, so I cannot really test that.

**Comment by kettenbach-it** [comment]
I can confirm this on MacOS 11.2 Big Sur with Oracle JDK 16

**Comment by kettenbach-it** [comment]
Using openjdk8 from brew will run it:

brew install openjdk@8

And then:
/usr/local/Cellar/openjdk@8/1.8.0+282/bin/java -jar yajhfc.jar

openjdk9 from adoptopenjdk won't work under Big Sur anymore, because of SIP.

Sooner or later Yajhfc on Mac OS will be dead, since the ancient JDKs won't run anymore and the JDKs after 10 won't have com.apple.awk anymore.

**Comment by jwolz** [comment]
I made a quick fix that should allow YajHFC to run if the com.apple.eawt.* classes cannot be found.

You can find a build including this fix under https://download.yajhfc.de/betas/

Lacking a Mac, it is not tested if this really works, however.
